-- Copies a list of every item in the game, along with their display names.
-- There is a comment at the bottom containing all of the items
-- There are of course some unobtainable items in this.
--[[ Unobainables [TO MY KNOWLEDGE]:
"AlrGun" - Deals 1 damage to enemies
"GhostKnife" - Knife the hidden shadow uses
"GhostBomb" - Bombs the hidden uses in Survival of the Fittest
"BInjector" - Powers up your fists, gives regeneration
"KitKnife" - Tier 4 kitchen knife [not sure if this is actually unobtainable]
"JBox" - Exotic SoF weapon - turns you into a slow, mini-gun wielding brute
"CRBSpear" - Explosive throwing spear
"LSMini" - Mini-gun the Juggernaut uses
"CMMaul" - Weapon from the Siege gamemode from SoF
"PSpray", "Taser", "PScanner" - Removed items from SoF
"RDio" - Does nothing??? Been in the game since UMG
"SClaw" - Weapon the shadows use, also from the PvE gamemode of SoF
"MusketR" - "Commisioned musket", joke variation of the decomissioned musket?
"GMSword" - Bright blue sword of the angel "Gabriel"
"EMSword" - Weapon from the Siege gamemode of SoF
"PLBlade" - Exotic SoF weapon [CAN TEAMKILL]
"Flare", "EFlare" - Sends a signal into the sky, does nothing now.
"SPCStim" - Has most of the buffs from the other stims
]]

local s = ""

for i,v in pairs(require(workspace.ServerStuff.Statistics.W_STATISTICS)) do
    s = s .. i .. " = '" .. v.name .. "', \n"
end

setclipboard(s)

--[[
AlrGun = 'Alarm Gun', 
PAxe = 'Pickaxe', 
STIPistol = 'STI DVC Limited Custom', 
CRPTrap = 'Crafted Punjis', 
TCaltrop = 'Steel Caltrops', 
TAxe = 'Hunting Axe', 
SAxe = 'Splitting Axe', 
PFork = 'Pitchfork', 
HuntingR = 'Remington 700', 
BPAKM = 'AKM Blueprint', 
GhostKnife = ''Polters Last Wish'', 
LSMini = 'TYPE-22 LSR-MG', 
EFlag = 'Opposers Flagpole', 
FAxe = 'Fire Axe', 
Ruger = 'Ruger LCP', 
CFlag = 'Company Flagpole', 
TJavelin = 'Throwing Javelin', 
RVolver = 'Peacemaker', 
MPistol = 'M1911A1', 
BPRSASS = 'RSASS Blueprint', 
MAid = 'First Aid Kit', 
CRPavise = 'Crafted Pavise', 
ImpN = 'Impact Grenade', 
BBat = 'Baseball Bat', 
CCleaver = 'Cleaver', 
BInjector = 'Berserk Injector', 
CRStone = 'Stone Rock', 
CMMaul = 'Commander's Maul', 
KSG = 'Kel-Tec KSG', 
CRBSpear = 'Bomb Spear', 
KitKnife = 'Kitchen Knife', 
SubLMG = 'M60-E6', 
CRSpear = 'Crafted Spear', 
PSpray = 'Pepper Spray', 
Hyperlame = 'Lameo-Blade', 
AgentCB = 'Agent Container 'Epsilon'', 
CRCaltrop = 'Crafted Caltrops', 
RDio = 'Handheld Radio', 
Mateba = 'Model 6 Unica', 
PScanner = 'Broken Tracker', 
ASVal = 'AS Val', 
CRBranch = 'Wood Branch', 
PBaton = 'Police Baton', 
Glock = 'Glock 17', 
FPan = 'Frying Pan', 
KaramB = 'Specialist Knife', 
HRifle = 'Winchester 940-1', 
SubMCX = 'MCX VIRTUS', 
LPipe = 'Lead Pipe', 
SubAK = 'AK-74', 
SubScar = 'FN SCAR-H', 
ESword = 'Estoc', 
GhostBomb = ''Polters Last Breath'', 
GSword = 'Great Sword', 
SClaw = 'Shadow Claws', 
NSword = 'Wakizashi', 
SSword = 'Short Sword', 
IbuP = 'Augmentin Antibiotics', 
SubMP = 'H&K MP5A3', 
CHammer = 'Construction Hammer', 
TKnife = 'Throwing Knife', 
CRRiggedE = 'Rigged Detonator', 
EBR = 'M14 EBR', 
CRBandage = 'Crude Bandage', 
MusketR = 'Commissioned Musket', 
TSpear = 'Tactical Spear', 
EMSword = 'Zealot's Blade', 
GMSword = 'Gabriel's Blade', 
SLauncher = 'Smoke Launcher', 
AgentCA = 'Agent Container 'Alpha'', 
Pistol = '.22 Broomhandle', 
BPExec = 'Executioner Blueprint', 
SUPAK = 'Modded AKM', 
RExplosive = 'Remote Explosive', 
CKnife = 'Combat Knife', 
DoubleShotgun = 'Caldwell 940', 
SSnare = 'Steel Snares', 
CRQuiver = 'Crafted Quiver', 
THawk = 'Tomahawk', 
RSASS = 'R11 RSASS', 
FAMAS = 'FAMAS F1', 
Flare = 'Airdrop Flare', 
PLBlade = 'PLASMA Broadsword', 
PTrap = 'Steel Punjis', 
PMine = 'Proximity Mine', 
EFlare = 'Emergency Airdrop Flare', 
RBow = 'Recurve Bow', 
CPBow = 'Compound MilBow', 
Splint = 'Immobilising Splint', 
CRJavelin = 'Crafted Javelin', 
BPAJM = 'A.J.M. 9 Blueprint', 
SCKnife = 'Scissors', 
Rifle = 'Modded Rifle', 
Tourni = 'Esmarch Tourniquet', 
DFAxe = 'Firerier Axe', 
FAid = 'Advanced IFAK', 
CRKnife = 'Crafted Knife', 
Rake = 'Rake', 
Yari = 'Yari', 
SUPMPistol = 'Modded Pistol', 
APack = 'Tactical Armour', 
BPack = 'Backpack', 
MShotgun = 'Model 870', 
DMusket = 'Decommissioned Musket', 
KShotgun = 'MVD KS-23', 
BPRifle = 'Rifle Blueprint', 
BPKSG = 'KSG Blueprint', 
PCutter = 'Pizza Cutter', 
MilAxe = 'Military Axe', 
BSpear = 'Boar Spear', 
BPNailed = ''Maria' Blueprint', 
TGas = 'Riot Grenade', 
BPHook = 'Billhook Blueprint', 
SPDStim = 'S44-UL1', 
CRVolver = 'Peacemaker Chain', 
HKnife = 'Hidden Knife', 
BPCPBow = 'Milbow Blueprint', 
BPSTI = 'Hi-Capa Blueprint', 
AgentCC = 'Agent Container 'Omicron'', 
CRCudgel = 'Crafted Cudgel', 
MRVolver = ''The Redeemer'', 
BHook = 'Artisan's Hook', 
HBerd = 'Halberd', 
CRStoneS = 'Stone Scrap', 
ExecSword = 'Executioner Sword', 
PKnife = 'Poisoned Knife', 
PKillers = 'Amoxicillin Tablets', 
Mac = 'Ingram MAC-10', 
URVolver = 'Peacemaker Uppercut', 
Dynamite = 'Dynamite', 
BadBat = 'The Bad Business', 
Molo = 'Fire Bomb', 
SPCStim = 'Compound Z', 
CBar = 'Crowbar', 
DEFStim = 'I4S-DS', 
DStim = '3-(cbSTM)', 
HStim = 'Cocktail "Perithesene"', 
Taser = 'Broken Taser', 
MGrenade = 'M67 Grenade', 
AJM = 'A.J.M. 9', 
ADBandage = 'Aseptic Bandage', 
CRSBomb = 'Crafted Smoke Bomb', 
Shovel = 'Shovel', 
VAlrGun = 'Alarming Gun', 
Fist = 'Fists', 
CRHatchet = 'Crafted Hatchet', 
AMR = 'PGM FR-12.7', 
NailedB = ''Maria'', 
MFork = 'Military Fork', 
RBHammer = ''The Decimator'', 
BPHammer = ''The Decimator' Blueprint', 
BPFAXE = 'Firerier Axe Blueprint', 
MMachete = 'Military Machete', 
IPick = 'Ice Axe', 
KarSniper = 'Karabiner 98k', 
CRBow = 'Crafted Bow', 
RPier = 'Rapier', 
SubVector = 'KRISS Vector', 
SPShotgun = 'SPAS-12', 
PSpear = 'Pike', 
DBarrel = 'Caldwell Handcannon', 
BKnuckles = 'Brass Knuckles', 
Avto = 'M1891 Avtomat', 
JBox = 'Juggernaut Kit', 
CRWoodS = 'Wood Scrap', 
SHammer = 'Sledgehammer', 
Deagle = 'Mark VII', 
BPMPistol = 'Pistol Blueprint', 
CRBPack = 'Crafted Backpack', 
SubMG = 'CBJ-MS PDW', 
CRNade = 'Crafted Explosive', 
SStim = 'BL1 (Neloprephine)', 
TStim = 'Used Stim', 
AdrStim = 'Hemostatic Zanustin', 
CRSplint = 'Crafted Splint', 
]]
