-- Only tested once, no idea if it works consistantly or not
-- Generated by Hydroxide's Upvalue Scanner: https://github.com/Upbolt/Hydroxide

local aux = loadstring(game:HttpGetAsync("https://raw.githubusercontent.com/Upbolt/Hydroxide/revision/ohaux.lua"))()

local scriptPath = game:GetService("Players").LocalPlayer.Backpack.mainHandler
local closureName = "unloadgun"
local upvalueIndex = 10
local closureConstants = {
	[1] = "ReplicatedStorage",
	[2] = "Weapons",
	[3] = "Name",
	[4] = "FindFirstChild",
	[5] = "ammo",
	[7] = "action"
}

local closure = aux.searchClosure(scriptPath, closureName, upvalueIndex, closureConstants)

debug.getupvalue(closure, upvalueIndex)["Shells"] = 2e9
debug.getupvalue(closure, upvalueIndex)["Small"] = 2e9
debug.getupvalue(closure, upvalueIndex)["Long"] = 2e9
debug.getupvalue(closure, upvalueIndex)["Short"] = 2e9
debug.getupvalue(closure, upvalueIndex)["Heavy"] = 2e9
debug.getupvalue(closure, upvalueIndex)["Medium"] = 2e9
debug.getupvalue(closure, upvalueIndex)["Light"] = 2e9